### ISSUE TITLE
any arm architecture support in future?

### ISSUE THREAD

**Issue by Rathna-K** [fhriley/kodi-headless-novnc#1]
HI I used to use lsioarmhf but since they abandoned this after 19, I am looking for options and I see you ported it over which is great! any chance you can port this to raspberry pi 4 / arm architecture? TIA

**Comment by fhriley** [comment]
This isn't a port. It's using the standard kodi PPA for Ubuntu. Unfortunately, they don't provide an arm build in the PPA.

**Comment by 0x0a11c0de** [comment]
@Rathna-K The `fhriley/kodi-headless-novnc:19.3` now supports both arm and arm64.
