### ISSUE TITLE
VNC Access

### ISSUE THREAD

**Issue by brando56894** [fhriley/kodi-headless-novnc#14]
After a lot of messing around, I discovered in the systemd service file for TigerVNC that it needs an SSH tunnel connection in order to work. It confused the hell out of me why I couldn't connect from a remote machine (or even locally using my IP instead of the loopback IP), even though netstat showed that it was listening on the proper port. 

It was only when I used **ssh -v -C -L 5900:localhost:5900 _my-servers-ip_** from my laptop and used TigerVNC to connect locally on my laptop using the loopback IP that I was finally able to connect and see the GUI.

I initially had issues with noVNC as well, but that turned out to be port related since I have a bunch of containers running and there were conflicts apparently.

**Comment by fhriley** [comment]
This should be fixed.
