### ISSUE TITLE
Setting credentials on vnc logon

### ISSUE THREAD

**Issue by acidzab** [fhriley/kodi-headless-novnc#15]
Hi,
it's possible to setup basic auth on both tigervnc and novnc for accessing to the headless kodi ?
Many thanks for any help

**Comment by thezoggy** [comment]
You cant unless you modify the file or use one of the forks of this project that have done this by modifying the Xtigervnc command in

https://github.com/fhriley/kodi-headless-novnc/blob/master/supervisord.conf#L20
from:
`-SecurityTypes None`
to:
`-SecurityTypes VncAuth,Plain -rfbauth /data/.vnc/passwd`


For info about rfbauth  see:
https://manpages.ubuntu.com/manpages/jammy/man1/Xtigervnc.1.html

**Comment by acidzab** [comment]
@thezoggy thanks that's what i did, i've created a fork of this project and modified the supervisord conf like you said, i close the issue
