### ISSUE TITLE
kodi log keeps giving error CActiveAESink::OpenSink - no sink was returned

### ISSUE THREAD

**Issue by jackydec** [fhriley/kodi-headless-novnc#2]
Hi, been trying your kodi headless container. working out great so far.

I do notice that my kodi.log gets filled up with errormessages : 

INFO <general>: CActiveAESink::OpenSink - initialize sink
ERROR <general>: CActiveAESink::OpenSink - no sink was returned
ERROR <general>: ActiveAE::InitSink - returned error

Can something be done to avoid these error messages?

Docker is running on a ubuntu server 20.4.3 LTS, which is running on Proxmox 7.0-11.

grtz,

Jacky

**Comment by fhriley** [comment]
Unfortunately, kodi does not have any settings to turn off trying to access sound hardware. The messages are harmless, and the only way to get rid of them would be to mount an alsa device into the container.

**Comment by fhriley** [comment]
@jackydec I actually found a fix for this. Please pull the image and recreate your container. Let me know if it fixes it for you.

**Comment by jackydec** [comment]
yes, issue solved with new container 👍
