### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by Vendo232** [fhriley/kodi-headless-novnc#4]
I managed to install it but it is not what I was expecting. At least in my setup it is quite laggy ( a lot ) but mainly there is no sound. Would you be able to help me how to enable sound?

**Comment by Vendo232** [comment]
my intention was to run this on Alexa Show in Silk browser. It runs but without sound

**Comment by fhriley** [comment]
This image is for a headless install, which means no monitor/tv. It is intended to be used as a central server to maintain your library. The GUI is available over HTTP so you can configure without needing another kodi instance. It will not work for playing videos or music.

**Comment by Vendo232** [comment]
Thank you, would you know if there is a Kodi which plays vide and sound in web browser?

**Comment by fhriley** [comment]
Actually, I take it back. Kodi has the chorus web interface on port 8080. I think that should work with this container. Give it a try and see if it works.
