### ISSUE TITLE
upnp not working?

### ISSUE THREAD

**Issue by jawrat** [fhriley/kodi-headless-novnc#6]
i've got your headless kodi working as expected and I can hit both the vnc and web browser sessions, but for some reason i'm unable to get upnp to work.  i've added the ports to the docker-compose file and enabled it in services, yet it doesn't seem to expose the ports outside the container.  using bash , it seems that it's actually listening on the correct ports for upnp, but no love from outside the container.  what am I doing wrong?

...
services:
  kodi:
   image: fhriley/kodi-headless-novnc
   restart: always
   init: true
   ports:
     - "1900:1900/udp"
     - "5000:5000/tcp"
     - "5900:5900/tcp"
     - "8000:8000/tcp"
     - "8080:8080/tcp"
     - "9090:9090/tcp"
     - "9777:9777/udp"
...

**Comment by fhriley** [comment]
I don't use upnp so I don't know anything about it. Have you [enabled](https://kodi.wiki/view/Settings/Services/UPnP_DLNA) and [configured](https://kodi.wiki/view/UPnP) it?

**Comment by jawrat** [comment]
thanks for the quick reply!  it's enabled and configured...it's something to do with the networking...when the docker container starts it sets up it's own network which isn't connected fully to the hosts' network.  exposing the ports *should* work, but for some reason it's not.  i'll see what I can play with in the docker-compose and maybe I can get it working by changing the network settings....

**Comment by fhriley** [comment]
As a guess, upnp probaby does some multicast, which means you'll need host networking mode. Add `network_mode: host` to your docker compose.

**Comment by jawrat** [comment]
that's the ticket.  it's most of the way there...just have to get the files to play nicely now.  but at least the upnp service is advertising now.  thanks!
