### ISSUE TITLE
Kodi crash with std::system_error  what():  Operation not permitted

### ISSUE THREAD

**Issue by sinopsysHK** [fhriley/kodi-headless-novnc#9]
Hello,

thank you for maintaining this container.

There are 2 issues (one a appearing beacause of the other).

My setup:  
- Host: I7 boxe
- OS: Ubuntu 20.04.5
- Docker: 20.10.1, build 831ebea

My script to launch the container:
```bash
docker run -d --init --name=mykodi \
-p 8093:8080 \
-p 9090:9090 \
-p 9777:9777/udp \
-p 5900:5900/tcp \
-p 8095:8000/tcp \
fhriley/kodi-headless-novnc:Nexus
```

Start of the container crash with attached logs:
[_mykodi_logs.txt](https://github.com/fhriley/kodi-headless-novnc/files/10495369/_mykodi_logs.txt)

```log
2023-01-25 01:47:03,534 INFO spawned: 'easy-novnc' with pid 59
2023-01-25 01:47:03,534 INFO spawned: 'easy-novnc' with pid 59
2023-01-25 01:47:03,539 INFO spawned: 'app' with pid 60
2023-01-25 01:47:03,539 INFO spawned: 'app' with pid 60
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f28abab7a7c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f28abab7a7c
stack: frame={sp:0x7ffe3c298970, fp:0x0} stack=[0x7ffe3ba99ec8,0x7ffe3c298f00)
0x00007ffe3c298870:  0x000000ffffffffff  0x0000000000000000 
[...]
runtime: unknown pc 0x7f28abab7a7c
stack: frame={sp:0x7ffe3c298970, fp:0x0} stack=[0x7ffe3ba99ec8,0x7ffe3c298f00)
0x00007ffe3c298870:  0x000000ffffffffff  0x0000000000000000 
[...] 

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc000040780 sp=0xc000040778 pc=0x4621e0
runtime.main()
	/usr/local/go/src/runtime/proc.go:174 +0x7b fp=0xc0000407e0 sp=0xc000040780 pc=0x43765b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x464401

rax    0x0
[...]

2023-01-25 01:47:03,546 INFO exited: easy-novnc (exit status 2; not expected)
2023-01-25 01:47:03,546 INFO exited: easy-novnc (exit status 2; not expected)
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
```

As raised in this log (2d issue):
```log
/usr/bin/kodi: 156: cannot create /data/kodi_crashlog-20230125_012740.log: Permission denied
```

This is because in the init script only the /data/.kodi, /data/.cache and /data/.config are assigned to app but not the parent folder /data which is used to create crash logs files

https://github.com/fhriley/kodi-headless-novnc/blob/2b24279b24d8b381aa13f8d703a203293ed6ea3e/docker-entrypoint.sh#L21

Once this issue worked around I have a pretty useless crash file:
[kodi_crashlog-20230125_014703.log](https://github.com/fhriley/kodi-headless-novnc/files/10495425/kodi_crashlog-20230125_014703.log)

**Comment by sinopsysHK** [comment]
Ok this is due to security feature in ubuntu + docker: cf
- [docker setup/ seccomp](https://docs.docker.com/engine/security/seccomp/)
- [similar issue](https://github.com/containers/skopeo/issues/1501)

workaround:
```bash
docker run -d --init --name=mykodi \
  --security-opt seccomp=unconfined \
  -p 8093:8080 \
  -p 9090:9090 \
  -p 9777:9777/udp \
  -p 5900:5900/tcp \
  -p 8095:8000/tcp \
  fhriley/kodi-headless-novnc:Nexus
```

Deactivating seccomp is not be a sustainable solution :( I haven't investigate further to find cleaner one...

**Comment by sinopsysHK** [comment]
For reference for anyone facing similar issue, based of [linuxserver.io FAQ](https://docs.linuxserver.io/faq#libseccomp) updating my docker engine to later version  5:20.10.23~3-0~ubuntu-focal made the trick !

**Comment by fhriley** [comment]
Thanks for figuring this out! I changed the entrypoint to change permissions on /data. I also added your link to the README.

**Comment by thezoggy** [comment]
another kodi-headless ran into this - cross referencing their issue as it has additional info -- https://github.com/matthuisman/docker-kodi-headless/issues/30
